import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "lulo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-slate-50 dark:bg-neutral-950'>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
